GET https://frozen-garden-30312.herokuapp.com/api/persons

###
GET https://frozen-garden-30312.herokuapp.com/info

###
GET https://frozen-garden-30312.herokuapp.com/api/persons/2

###
DELETE https://frozen-garden-30312.herokuapp.com/api/persons/4

###
POST https://frozen-garden-30312.herokuapp.com/api/persons
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "85-82344"
}
